name: "SOLAR Lab at UMass Amherst"
# url: https://adamlechowicz.github.io/solar-lab-site/
url: https://solar.cs.umass.edu

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  # - key: visitor
  #   name: Visitors
  - key: adminstaff
    name: Administrative Staff
  - key: staff
    name: Postdocs
  - key: grad
    name: Graduate Students
  - key: alum
    name: PhD and Postdoc Alumni
  - key: ugrad
    name: Undergraduate Students

# Number of news stories on the front page.
front_page_news: 5

# Base pathname for links.
# base: "/solar-lab-site"

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /people.html
  - title: Publications
    link: /publications.html
  - title: Projects
    link: /research.html
  - title: News
    link: /blog.html
  # - title: Code
  #   link: /code.html
  # - title: Wiki
  #   link: http://lass.cs.umass.edu/wiki/

google_analytics: 'G-FFZJ53219K'

scholar:

  style: apa
  locale: en

  source: /bib
  bibliography: pubs.bib
  bibliography_template: bib
  # Note: if you have latex math in your bibtex, the latex filter
  # preprocessing may conflict with MathJAX if the latter is enabled.
  # See https://github.com/alshedivat/al-folio/issues/357.
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"
